# Generated by Django 3.2.5 on 2021-07-31 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checklists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=100)),
                ('check_details', models.TextField()),
                ('check_vuln_root_cause', models.TextField()),
                ('check_remediation', models.TextField()),
                ('check_tags', models.TextField()),
                ('check_patch_references', models.TextField()),
                ('check_exploit_references', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='NONAME', max_length=100)),
                ('project_date_created', models.DateField(auto_now=True)),
                ('project_date_last_executed', models.DateField(auto_now=True)),
                ('project_status', models.CharField(choices=[('NOT STARTED', 'The project is not yet started'), ('RUNNING', 'The project is running now'), ('STOPPED', 'The was running earlier, but now it is stopped'), ('COMPLETED', 'The project has finished execution')], default='NOT STARTED', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_is_3rd_party', models.BooleanField()),
                ('tool_satisfies_m001', models.BooleanField(default=False)),
                ('tool_satisfies_m002', models.BooleanField(default=False)),
                ('tool_satisfies_m003', models.BooleanField(default=False)),
                ('tool_satisfies_m004', models.BooleanField(default=False)),
                ('tool_satisfies_m005', models.BooleanField(default=False)),
                ('tool_satisfies_m006', models.BooleanField(default=False)),
                ('tool_deployed_as_docker', models.BooleanField(default=False)),
                ('tool_deployed_as_python_script', models.BooleanField(default=False)),
                ('tool_deployed_as_bash_script', models.BooleanField(default=False)),
                ('tool_deployed_as_powershell_script', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methodology_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfb.projects')),
            ],
        ),
    ]
