# Generated by Django 3.2.5 on 2021-08-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfb', '0002_methodology_methodology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklists',
            name='check_details',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklists',
            name='check_exploit_references',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklists',
            name='check_patch_references',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklists',
            name='check_remediation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklists',
            name='check_tags',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='checklists',
            name='check_vuln_root_cause',
            field=models.CharField(max_length=100),
        ),
    ]
